#REQUEST For getting all users
GET http://localhost:3000/users

###
#REQUEST FOR GETTING A User Profile
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwY2M3OTM0YmQwZDAxOTRkNDA1MmQiLCJpYXQiOjE2MDc1MTkzNTR9.Yn5vrNmk1d0s7FuRIC7RKSikg-a87WiZcHMK9WX6wb4

###
#REQUEST FOR logging out A User Profile
POST http://localhost:3000/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwY2M3OTM0YmQwZDAxOTRkNDA1MmQiLCJpYXQiOjE2MDc1MTkzNTR9.Yn5vrNmk1d0s7FuRIC7RKSikg-a87WiZcHMK9WX6wb4

###
#REQUEST for logging out all sessions for a user
POST http://localhost:3000/users/logoutAll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwY2M3OTM0YmQwZDAxOTRkNDA1MmQiLCJpYXQiOjE2MDc1MTkzNTR9.Yn5vrNmk1d0s7FuRIC7RKSikg-a87WiZcHMK9WX6wb4


###
#REQUEST FOR Creating A User
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Minato Uzumaki",
    "email": "korer54257@hmnmw.com",
    "password": "12345678"
}

###
#REQUEST FOR Updating A User
PATCH  http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwY2M3OTM0YmQwZDAxOTRkNDA1MmQiLCJpYXQiOjE2MDc1MTkzNTR9.Yn5vrNmk1d0s7FuRIC7RKSikg-a87WiZcHMK9WX6wb4
Content-Type: application/json

{
    "name": "minato naruto",
    "email": "naruto@gmail.com",
    "password": "narutowastheone"
}

###
#REQUEST FOR Deleting a user
DELETE http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwY2M3OTM0YmQwZDAxOTRkNDA1MmQiLCJpYXQiOjE2MDc1MTkzNTR9.Yn5vrNmk1d0s7FuRIC7RKSikg-a87WiZcHMK9WX6wb4


###
#REQUEST FOR Login a user
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "naruto@gmail.com",
    "password": "narutowastheone"
}



####################################

###
#REQUEST FOR GETTING ALL TASKS
GET http://localhost:3000/tasks?sortBy=createdAt_desc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwY2M3OTM0YmQwZDAxOTRkNDA1MmQiLCJpYXQiOjE2MDc1MTkzNTR9.Yn5vrNmk1d0s7FuRIC7RKSikg-a87WiZcHMK9WX6wb4

###
#REQUEST FOR Creating A Task
POST http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwY2M3OTM0YmQwZDAxOTRkNDA1MmQiLCJpYXQiOjE2MDc1MTkzNTR9.Yn5vrNmk1d0s7FuRIC7RKSikg-a87WiZcHMK9WX6wb4
Content-Type: application/json

{
    "description": "Watched CLOY",
    "complete": "true"
}

###

#REQUEST FOR Updating A Tasks
PATCH  http://localhost:3000/tasks/5fcf7c635172e31f40f1ae9c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwY2M3OTM0YmQwZDAxOTRkNDA1MmQiLCJpYXQiOjE2MDc1MTkzNTR9.Yn5vrNmk1d0s7FuRIC7RKSikg-a87WiZcHMK9WX6wb4
Content-Type: application/json

{
    "description": "Learned Node Beginning",
    "complete": "true"
    
}

###
#REQUEST FOR Deleting a tasks

DELETE http://localhost:3000/tasks/5fcf7c635172e31f40f1ae9c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwY2M3OTM0YmQwZDAxOTRkNDA1MmQiLCJpYXQiOjE2MDc1MTkzNTR9.Yn5vrNmk1d0s7FuRIC7RKSikg-a87WiZcHMK9WX6wb4

###
#REQUEST FOR getting a task by id
GET http://localhost:3000/tasks/5fcf7c635172e31f40f1ae9c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQwY2M3OTM0YmQwZDAxOTRkNDA1MmQiLCJpYXQiOjE2MDc1MTkzNTR9.Yn5vrNmk1d0s7FuRIC7RKSikg-a87WiZcHMK9WX6wb4




